CREATE TABLE usuarios(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
role VARCHAR(15) NOT NULL,
senha VARCHAR(50) NOT NULL,
profissional VARCHAR(255) NOT NULL,
contato VARCHAR(255) NOT NULL UNIQUE
);